version: '3.5'

services:
  db-mongo:
    image: mongo
    volumes:
      - mongo-data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      backend:
        aliases:
          - db-mongo
  
  backend:
    build:
      context: backend-maslow
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - db-mongo
    networks:
      - backend
      - frontend
  
  frontend:
    build:
      context: frontend-maslow
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    networks:
      - frontend

volumes:
  mongo-data-volume:

networks:
  backend:
    name: backend-network
  frontend:
    name: frontend-network